language: node_js

node_js:
  - "9.5.0"

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - sysconfcpus

install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install elm -g
  - npm install elm-test -g
  - elm package install -y
  - cd tests
  - npm install
  - elm package install -y
  - cd ..

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 'elm-make'
  - cd tests
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make'
  - cd ..
  - npm test