language: node_js

node_js:
  - "9.5.0"

cache:
  directories:
    - sysconfcpus

install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install elm -g
  - npm install elm-test -g
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm-make with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old "$@"' > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - elm package install -y
  - cd tests
  - npm install
  - elm package install -y
  - cd ..

script:
  - cd src/elm
  - elm-make --output=/dev/null --yes
  - cd ../../tests
  - elm-make --output=/dev/null --yes
  - cd ..
  - npm test